language:
    - node_js

node_js:
    - "0.12"

before_install:
    - "curl https://install.meteor.com | sh"
    - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
    - "npm install -g spacejam"
    
before_script:
    - "export PATH=$HOME/.meteor:$PATH"
    
services:
  - mongodb

env:
    - 'LAIKA_OPTIONS="-t 5000"'

script:
    - "spacejam test-packages ./"
