language:
    - node_js

node_js:
    - "0.12"

before_install:
    - "curl https://install.meteor.com | sh"
    - "npm install -g spacejam"
    
before_script:
    - "export PATH=$HOME/.meteor:$PATH"

env:
    - LAIKA_OPTIONS="-t 5000"

script:
    - "spacejam test-packages ./"
