language:
    - node_js

node_js:
    - "0.12"

before_install:
    - "curl https://install.meteor.com | sh"
    - "npm install -g spacejam"
    
before_script:
    - "export PATH=$HOME/.meteor:$PATH"

script:
    - "spacejam test-packages ./meteor"
